### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by Chriswilldo** [thedigicraft/Atom.CMS#100]
So I finished the series, and almost everything works fine, however on the front end of the site, only my home page will load up. about shows nothing when u click it and same with contact. It's almost as if you can't change it using the back end because when i tried to with the page manager it doesn't work. If i try editing it, it'll just say page added which shows true on phpmyadmin, but it doesn't actually update the site. It's almost like the front end and back end of the site aren't coding correctly to each other. If anyone knows what the issue could be that'd be swell. Ive re-checked my coding a lot and I don't think I made much mistakes overall.

**Comment by creptor** [comment]
the description of the error you're giving me is kind of poor, I can't figure out wich is your problem because i cant anderstand you, please be more precise in what doesn't work, where is not working, how is it different from the video, and if you have and url (online host) give it to me so I can see the problem. Any extra info about this error will help, and try to keep it simple, one error at a time.

**Comment by Chriswilldo** [comment]
Sorry about that. I'll upload screenshots of what i mean. 
![home page](https://cloud.githubusercontent.com/assets/8390023/6182191/5ec3c944-b304-11e4-9d08-64b7d04960ef.PNG)

**Comment by creptor** [comment]
can't see the error there please just describe your problem and how it should be working. like: the urls seems to be missconfigured so I can't get the right pages, or The content is not display has it is on my db. If you need more info of your error enable error reporting from php, that usually gives pretty acuareate errors.

**Comment by Chriswilldo** [comment]
I updated the comment I posted above you. Other than that, everything seems to be working fine. The only two main issues is that my page manager isn't working; won't edit, and my website will only show the Home page's content. 
Debug and Navigation works fine. I can still switch Home and about, but the actual content for the about site won't show up. Also view array doesn't show on debug but I'll fix that if needed.
![navigation and debug example](https://cloud.githubusercontent.com/assets/8390023/6182337/93f86ca2-b307-11e4-8c54-e019857d1c9e.PNG)
The conent for About and contact exist on page manager, but for some reason it doesn't want to show up...
![about pm](https://cloud.githubusercontent.com/assets/8390023/6182358/f8850c02-b307-11e4-9eeb-18c65d3e3f40.PNG)...

If you need to see my coding for anything let me know.

**Comment by Chriswilldo** [comment]
I guess my main question is, do you think it's fixable, or am I going to have to restart all over?

**Comment by creptor** [comment]
I know what it is, thank you for giving me that good question. I the endings of the videos the function for the pages was change right, so maybe you change them in the wrong file. so you toguht you change the admin version but you were changing the web version please check that.

**Comment by Chriswilldo** [comment]
what part of the series do you mean?

**Comment by Chriswilldo** [comment]
I am not entirely sure on what you mean. Where part of the series are specifying about?

**Comment by creptor** [comment]
in the series he changed the functions page to data_post in the data.php, please give me that file along with your setup.php for the admin and for the normal pages please. (also please use [pastebin](http://pastebin.com/))

**Comment by Chriswilldo** [comment]
Ah. Well I think that is the issue indeed. Here you are sir, i posted my data.php and setup.php on pastebin. Both the admin and non-admin versions to compare the both. Because I do believe that I got the two mixed up at one point. I also somehow have 100 hits on those files on pastebin. Not sure what that means but I'm guessing views? Already?....

http://pastebin.com/u/Chriswilldo

**Comment by creptor** [comment]
I can't find your issue :cry:, could you try to remove that error_reporting to see what error does it throw out in the broquen pages? or use: `error_reporting(-1);`

**Comment by huniz** [comment]
I have a same problem with @Chriswilldo. I think the tutor forgot to connect the navigation and pages. I think he tried to setup navigation as menu bar on the front page and the 'posts' as sub-pages under that menu created from the navigation. So the navigation is showing up in the frontpage rather than the initial pages created in the video up to about 60(? i think). I am not sure but the 'post_type' is related to  the main page and sub posts. PLEASE HELP US

**Comment by creptor** [comment]
please use that `error_reporting(-1);` as a replacement to the `error_reporting(1);`or 0 wathever and tellme wich error do you get. I can't fix it if you don't give one, because I can find the code mess up :cry:.

**Comment by thedigicraft** [comment]
I do seem to remember forgetting something in the navigation at one point.  I will have to watch the videos when I am at home to be sure.

**Comment by huniz** [comment]
Thank you so much @thedigicraft !!!
Your tutorials were amazing and hope you to continue!

**Comment by huniz** [comment]
I think we brought the front menu from the navigation in our server. But the front page index is not pulling the page from the navigation.

**Comment by thedigicraft** [comment]
Thanks @huniz !

I am in agreement with @creptor. Try running this with the ```error_reporting(0);```.  That way we can see if there are any errors.  Specifically within your queries.  I looked at your data.php and it seems to match up with the one here on github.  

One thing I did notice is your URL.  The directory in which you have saved this CMS has characters in it that do not always jive.  Try taking out any spaces and/or special characters such as # out of your url.

**Comment by thedigicraft** [comment]
Also.  Could you get me a screenshot of the debug panel that includes the ```$path``` array please :-)

**Comment by huniz** [comment]
The files are exactly the same with the most recent files on the Github. Sorry that I am not able to grab screenshots.

So my point is that how can I write something on the front pages created from navigation??
The most recent pages are set to the sortable navigation and I am not sure about how to connect them to actual working php

**Comment by creptor** [comment]
Another thing to have in mind... the pages actually have a page type thing, where you define wich page file it should load to display it's content, please meake sure the values have been correctly introduced to your database. That could make pages not visibles(or at least the title, content, etc) but everyting else work.... just like in your screenshots, where the index works but the others just display the navigastion and the footer

**Comment by Chriswilldo** [comment]
alright so i got good news and bad news. The good news. I found the problem. The bad news. I am not entirely sure on how to solve them. By the way error reporting -1 helped me find those problems. Sorry for not doing this earlier. I forget to check my emails sometimes. It seems that I have a lot of errors...... It seems that I messed up a lot in my sandbox.php. I shall paste my pix below.
Home
![error 1](https://cloud.githubusercontent.com/assets/8390023/6428005/cff364a8-bf57-11e4-99ed-1683be065b10.PNG)
Contact me
![error 2](https://cloud.githubusercontent.com/assets/8390023/6428008/d8c8f746-bf57-11e4-892a-d0cd23813e09.PNG)
The Abouts
![error2 1](https://cloud.githubusercontent.com/assets/8390023/6428018/feb35f14-bf57-11e4-86b2-6bfa18d312c2.PNG)
Page Manager
![error 3](https://cloud.githubusercontent.com/assets/8390023/6428019/0ddef246-bf58-11e4-8225-cce5779c78f2.PNG)
User Manager
![error 4](https://cloud.githubusercontent.com/assets/8390023/6428021/15e4d190-bf58-11e4-9dcb-a46f0126ace3.PNG)

**Comment by creptor** [comment]
wow those pages look awful :C I'll look into then in a minute please wait :3

**Comment by Chriswilldo** [comment]
Why thank you. Hahaha alright thanks. And if you need to see the specific coding for those lines let me know. Matter of fact I'll just show you them just in case

**Comment by creptor** [comment]
allrigth, please read that, it's related to the problem you're having with the pages.... https://github.com/thedigicraft/Atom.CMS/issues/100#issuecomment-76544014 It's just what I published

That sandbox error is common in the way the page haddles things

add this `if(!isset($opened)){$opened=NULL;}` to the confing.php in the admin section to remove that error, and check the ON SUBMIT erros, not just the page, you actually have to submit something to display query errors.

**Comment by Chriswilldo** [comment]
Yeah about that... is there a config.php? Because I don't have one....

**Comment by creptor** [comment]
this is the file in this repository: https://github.com/thedigicraft/Atom.CMS/blob/master/admin/config/setup.php

**Comment by Chriswilldo** [comment]
So i added that code but it doesn't show the error anymore nor did it solve it. I'm gonna re-compare my code again to see if that'll fix some of the errors.

**Comment by Chriswilldo** [comment]
Another thing. When I was simplifying the index.php I was having a lot of trouble making it work. Now it seems like that issue is still somewhat present. Any suggestions or is this as hard to fix as i thought?

**Comment by creptor** [comment]
I would like to stay in the issue, if you're having another you can create other and work on both at the same time, please do it to keep things organized.

**Comment by Chriswilldo** [comment]
I think i might start over to see.

**Comment by creptor** [comment]
allright, sometimes is the best and necesary way to find errors
